<a href="https://colab.research.google.com/github/qianlinnian/Pytorch-learning/blob/main/Pytorch_baseuse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Colab 常用快捷键

* **Ctrl + M + B**: 在下方插入新单元格
* **Ctrl + M + A**: 在上方插入新单元格
* **Ctrl + M + D**: 删除单元格
* **Ctrl + Enter**: 运行当前单元格
* **Shift + Enter**: 运行当前单元格并跳转到下一个单元格
* **Ctrl + Shift + Enter**: 运行当前单元格并向下滚动以显示下一个单元格
* **Ctrl + M + M**: 将 code 单元格转变为文本单元格 (Markdown)
* **Ctrl + M + Y**: 将文本单元格 (Markdown) 转变为 code 单元格
* **Ctrl + S**: 保存笔记本
* **Ctrl + /**: 注释/取消注释代码
* **Tab**: 代码自动补全

您可以在菜单栏中的“工具”->“键盘快捷键”中找到更多快捷键设置。

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [ ]:
Tensor = torch.tensor([[[1,2,3,4],[1,2,3,4],[1,2,3,4]],
             [[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
Tensor

tensor([[[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]],

        [[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]]])

In [ ]:
Tensor.ndim

3

In [ ]:
Tensor.shape

torch.Size([2, 3, 4])

In [ ]:
random_tensor = torch.rand(1,3,4)
print(random_tensor)


tensor([[[0.2456, 0.8353, 0.0618, 0.0436],
         [0.1574, 0.0849, 0.6714, 0.0808],
         [0.8220, 0.4579, 0.8565, 0.1962]]])


In [ ]:
Tensor_A = torch.rand(3,4)
Tensor_A

tensor([[0.0459, 0.2974, 0.2045, 0.0248],
        [0.7078, 0.4720, 0.9029, 0.9771],
        [0.1755, 0.9857, 0.3815, 0.6250]])

In [ ]:
Tensor_B = torch.zeros(3, 4)  # 创建同样形状的张量
Tensor_B.copy_(Tensor_A)      # 注意是 copy_() 不是 copy()
print(Tensor_B)

print('\n',Tensor_B.T)

tensor([[0.0459, 0.2974, 0.2045, 0.0248],
        [0.7078, 0.4720, 0.9029, 0.9771],
        [0.1755, 0.9857, 0.3815, 0.6250]])

 tensor([[0.0459, 0.7078, 0.1755],
        [0.2974, 0.4720, 0.9857],
        [0.2045, 0.9029, 0.3815],
        [0.0248, 0.9771, 0.6250]])


In [ ]:
Tensor_C = torch.rand(20).type(torch.int64)

Tensor_C.argmin()

tensor(0)